### ISSUE TITLE
offscreen strings shouldn't display message

### ISSUE THREAD

**Issue by ConfusedVorlon** [onesky/auto-screenshot-ios#1]
I have a lot of offscreen strings, so displaying a message at the top (one every 5 seconds) can be really annoying.

I'd suggest just outputting that data to the log. It doesn't seem like critical info.

**Comment by myabc** [comment]
:+1:

**Comment by bretdabaker** [comment]
Fixed in https://github.com/onesky/auto-screenshot-ios/releases/tag/v0.9.7
