### ISSUE TITLE
Crash from start

### ISSUE THREAD

**Issue by FlorianBasso** [onesky/auto-screenshot-ios#12]
Hi !

I tried to import this framework but as soon as my app starts, it crashes.

I have this error but I don't know how I can fix it.

`Assertion failed: ([NSStringFromSelector(_cmd) isEqualToString:@"localizedStringForKey:value:table:"]), function __replace_localizedStringForKey_value_table_IMP, file /Users/bretcheng/Dropbox/Projects/OneSky/OneSkyScreenshotHelper/iOS/OneSkyScreenshotHelper/Dependencies/NSBundle+OSSSwizzle.m, line 20.
`

**Comment by maggieonesky** [comment]
Hi, thank you for your details. Which iOS version are you using? We will have an engineer investigate your issue as soon as we can. Thanks!

**Comment by FlorianBasso** [comment]
Hi, sorry for my late reply. I have this crash on every iOS version. (10.2, 8.3, 9.1, etc...)
I think the issue is the file that is used. Why does it use /Users/bretcheng/Dropbox ?

**Comment by bretdabaker** [comment]
Our SDK swizzles `localizedStringForKey:value:table` so there will be problems if you also swizzle that method. The swizzling is needed to identify the keys from the displayed strings for tagging, so you will need to comment out your code during development in order for the SDK to work.
