### ISSUE TITLE
Screenshots are not automatically tagged

### ISSUE THREAD

**Issue by damienmollard** [onesky/auto-screenshot-ios#6]
Hi, I've tried the demo project and screenshots are not automatically tagged

![capture d ecran 2015-12-17 a 10 37 20](https://cloud.githubusercontent.com/assets/5597632/11866263/347f1164-a4aa-11e5-9e58-c8a219d77882.png)

**Comment by bretdabaker** [comment]
Did you upload the .strings files in the demo project to your project on OneSky? No strings will be tagged if the .strings files are not available in the project.
