### ISSUE TITLE
error uploading screenshots to OneSky server: unsupported URL

### ISSUE THREAD

**Issue by agustinus** [onesky/auto-screenshot-ios#7]
We're using swift and the latest released library. We see this error every time we take a screenshot:

```
OneSkyScreenshotHelper - uploading 1 screenshot(s) to server
OneSky: error uploading screenshots to OneSky server: unsupported URL
```

**Comment by bretdabaker** [comment]
It usually happens when the API key/secret and project id isn't set up correctly, please check and let me know if there are more information in the debug log.

**Comment by nendyjr** [comment]
Hi Bretdabaker,
I have same issue.
From admin page i got, public key and secret key, while in your SDK just have apiKey and apiSecret.
So how relating those key to your SDK Attribute.

Thank you.

**Comment by bretdabaker** [comment]
API key > public key in site settings/admin page
API secret > secret key in site settings/admin page
![screen shot 2016-05-13 at 4 57 28 pm](https://cloud.githubusercontent.com/assets/990341/15243055/06b9e1cc-192c-11e6-886b-91882dcf9b35.png)

project id > can be found under project name
![screen shot 2016-05-13 at 4 56 18 pm](https://cloud.githubusercontent.com/assets/990341/15242999/b3f845be-192b-11e6-8e4d-6d58a2e52259.png)

Code example:
```objc
[[OneSkyScreenshotHelper sharedHelper] setProjectId:@"39146"];
[[OneSkyScreenshotHelper sharedHelper] setApiKey:@"KSD4345SDKSfs4534fgSjasKs23R"];
[[OneSkyScreenshotHelper sharedHelper] setApiSecret:@"ksd8N695BowbHZJEqSrhQesasw34wgX"];
[[OneSkyScreenshotHelper sharedHelper] startSession];
```

**Comment by agustinus** [comment]
I've double checked the project id, api key and api secret, all are correct. 
Do you have example how to implement it using swift. I get this from the other thread:
```
 var helper:OneSkyScreenshotHelper = OneSkyScreenshotHelper.sharedHelper() as OneSkyScreenshotHelper
        helper.projectId = "Your Project ID"
        helper.apiKey = "Your API Key"
        helper.apiSecret = "Your API Secret"
        helper.startSession();

```
But it seems it's not relevant to the latest xcode? I'm using xcode 7.3. 
Thanks.

**Comment by bretdabaker** [comment]
I have just tried the helper using Swift, and it's working as expected.

Swift code example:
```swift
let helper = OneSkyScreenshotHelper.sharedHelper() as! OneSkyScreenshotHelper
helper.apiKey = "Your API Key"
helper.apiSecret = "Your API Secret"
helper.projectId = "12345"
helper.startSession()        
```
Here is a demo project:
[auto-screenshot-ios-swift-test.zip](https://github.com/onesky/auto-screenshot-ios/files/262958/auto-screenshot-ios-swift-test.zip)

**Comment by agustinus** [comment]
Thank you, it's working now.
And yes, I put the api secret wrongly.
